### ISSUE TITLE
Codestyle version is pretty old

### ISSUE THREAD

**Issue by dickschoeller** [sivakumar-kailasam/codeclimate-checkstyle#4]
I started trying to get my project moved over to using Code Climate for Checkstyle analysis and I discovered that the version I've been using. In particular 7.2 introduced an improvement to DesignForExtension that is very useful for anybody using Bean annotations.

Any chance of getting a newer version of Checkstyle?

**Comment by sivakumar-kailasam** [comment]
Absolutely. Do you want to try doing that via a PR?

**Comment by dickschoeller** [comment]
I could do that. Is there any standard way to test these engines before
submitting changes?

**Comment by sivakumar-kailasam** [comment]
the usual way is to publish the docker image to local with tag codeclimate/codeclimate-checkstyle and try it in an actual app. But since we're already on 7.0, it should be fairly safe to upgrade
